### ISSUE TITLE
jquery-3.2.1.min.js

### ISSUE THREAD

**Issue by falinhares** [groundworkcss/groundwork#282]
Groundworks uses jquery-1.10.2.min.js to run. My system is using jquery-3.2.1.min.js which is newer. Console log shows some problems because I changed versions:

jquery-3.2.1.min.js:4 Uncaught TypeError: a.indexOf is not a function
    at r.fn.init.r.fn.load (jquery-3.2.1.min.js:4)
    at groundwork.all.js:1
    at groundwork.all.js:1
r.fn.load @ jquery-3.2.1.min.js:4
(anonymous) @ groundwork.all.js:1
(anonymous) @ groundwork.all.js:1
jquery-3.2.1.min.js:2 jQuery.Deferred exception: a.indexOf is not a function TypeError: a.indexOf is not a function
    at r.fn.init.r.fn.load (http://localhost/automproc/js/jquery-3.1.1.min.js:4:19062)
    at HTMLDocument.<anonymous> (http://localhost/automproc/js/groundwork.all.js:1:7208)
    at j (http://localhost/automproc/js/jquery-3.2.1.min.js:2:29999)
    at k (http://localhost/automproc/js/jquery-3.2.1.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 jQuery.Deferred exception: $(...).placeholderText is not a function TypeError: $(...).placeholderText is not a function
    at HTMLDocument.<anonymous> (http://localhost/automproc/js/groundwork.all.js:1:14733)
    at j (http://localhost/automproc/js/jquery-3.2.1.min.js:2:29999)
    at k (http://localhost/automproc/js/jquery-3.2.1.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 jQuery.Deferred exception: $(...).responsiveTables is not a function TypeError: $(...).responsiveTables is not a function
    at HTMLDocument.<anonymous> (http://localhost/automproc/js/groundwork.all.js:1:16692)
    at j (http://localhost/automproc/js/jquery-3.2.1.min.js:2:29999)
    at k (http://localhost/automproc/js/jquery-3.2.1.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 jQuery.Deferred exception: $(...).not(...).responsiveText is not a function TypeError: $(...).not(...).responsiveText is not a function
    at HTMLDocument.<anonymous> (http://localhost/automproc/js/groundwork.all.js:1:18532)
    at j (http://localhost/automproc/js/jquery-3.2.1.min.js:2:29999)
    at k (http://localhost/automproc/js/jquery-3.2.1.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 Uncaught TypeError: a.indexOf is not a function
    at r.fn.init.r.fn.load (jquery-3.1.1.min.js:4)
    at HTMLDocument.<anonymous> (groundwork.all.js:1)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
r.fn.load @ jquery-3.1.1.min.js:4
(anonymous) @ groundwork.all.js:1
j @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 Uncaught TypeError: $(...).placeholderText is not a function
    at HTMLDocument.<anonymous> (groundwork.all.js:1)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
(anonymous) @ groundwork.all.js:1
j @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 Uncaught TypeError: $(...).responsiveTables is not a function
    at HTMLDocument.<anonymous> (groundwork.all.js:1)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
(anonymous) @ groundwork.all.js:1
j @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
jquery-3.2.1.min.js:2 Uncaught TypeError: $(...).not(...).responsiveText is not a function
    at HTMLDocument.<anonymous> (groundwork.all.js:1)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)

How can I fix this?

**Comment by falinhares** [comment]
Found the solution at
https://stackoverflow.com/questions/38871753/uncaught-typeerror-a-indexof-is-not-a-function-error-when-opening-new-foundat

at the groundwork.all.js change all $(window).load(function(){...}); with $(window).on('load', function(){ ...});
